SELECT TOP (1000) [InspectionID]
      ,[ProductID]
      ,[EmployeeID]
      ,[InspectionDate]
      ,[InspectionStatus]
      ,[InspectionScore]
      ,[Notes]
      ,[CreatedDate]
  FROM [AdventureWorks2022].[dbo].[WarehouseInspection]