version: '3.9'

services:
  sqlserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sqlserver-dev
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      SA_PASSWORD: "Test123#$%^&"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup
    restart: unless-stopped

volumes:
  sqlserver_data: